// apps/next-website-app-dir/app/articles/page.tsx
import { sanityConfig } from "@/lib/config/envVariables";
import { getAllArticles } from "common/src/content/sanity/articles";
import Link from "next/link";

export const revalidate = 3600; // every hour

// SEO
export async function generateMetadata() {
	return {
		title: "All articles",
		description: `A list of all articles`,
	};
}

async function getData() {
	const allArticles = await getAllArticles(sanityConfig);
	return allArticles;
}

export default async function ArticleListPage() {
	const allArticlePageDocuments = await getData();

	return (
		<>
			<h1>Article list</h1>
			<ul>
				{allArticlePageDocuments.map((article) => {
					return (
						<li key={article._id}>
							<Link href={`articles/${article.collection.path.current}/${article.slug}`}>
								{article.title}
							</Link>
						</li>
					);
				})}
			</ul>
		</>
	);
}

// apps/web-sveltekit-intl/src/routes/[lang]/articles/+page.svelte
<script lang="ts">
	import { page } from "$app/stores";
	import SEO from "$lib/components/SEO.svelte";
	import type { PageData } from "./$types";

	export let data: PageData;
</script>

<SEO
	pageType={"website"}
	title="All articles"
	description="A list of all articles"
	permalink={$page.url.pathname}
	publishDate={null}
/>
<h2>Article list</h2>
<ul>
	{#each data.articles as article}
		<li><a href={`/articles/${article.collection.path.current}/${article.slug}`}>{article.title}</a></li>
	{/each}
</ul>
