// web-studio/apps/web-sveltekit/src/lib/components/landingPage/hero.svelte
<script lang="ts">
	// imports
	import type { PageItemHero } from "common/src/types/sanity/landingPage/pageItemHero";

	// props
	export let heroData: PageItemHero;
</script>

<div class="bg-blue-500 px-4 py-2 text-center">
	<h3>{heroData.title}</h3>
	<p>{heroData.bodyText}</p>
	<a href={heroData.callToActionUrl}>{heroData.callToActionLabel}</a>
</div>

// apps/next-website/lib/components/landingPage/hero/index.tsx
import { PageItemHero } from "common/src/types/sanity/landingPage/pageItemHero";
import { LinkButton } from "ui";

interface Props {
	data: PageItemHero;
}

export default function LandingPageHero({ data }: Props) {
	const title = data.title;
	const bodyText = data.bodyText;
	const callToActionLabel = data.callToActionLabel;

	return (
		<div className="bg-blue-500 px-4 py-2 text-center">
			<h3>{title}</h3>
			<p>{bodyText}</p>
			<LinkButton href={data.callToActionUrl}>{callToActionLabel}</LinkButton>
		</div>
	);
}
