// apps/web-sveltekit-intl/src/lib/components/landingPage/callToActionBar.svelte
<script lang="ts">
	// imports
	import type { PageItemCallToActionBar } from "common/src/types/sanity/landingPage/pageItemCallToActionBar";

	// props
	export let ctaBarData: PageItemCallToActionBar;
</script>

<div class="bg-red-400 px-4 py-2">
	<div>
		<p>{ctaBarData.bodyText}</p>
		<a href={ctaBarData.callToActionUrl}>{ctaBarData.callToActionLabel}</a>
	</div>
</div>

// apps/next-website/lib/components/landingPage/callToActionBar/index.tsx
import { PageItemCallToActionBar } from "common/src/types/sanity/landingPage/pageItemCallToActionBar";
import Link from "next/link";

interface Props {
	data: PageItemCallToActionBar;
}

export default function LandingPageCallToActionBar({ data }: Props) {
	const bodyText = data.bodyText;
	const callToActionLabel = data.callToActionLabel;

	return (
		<div className="bg-red-400 px-4 py-2">
			<div>
				<p>{bodyText}</p>
				<Link href={data.callToActionUrl} passHref>
					{callToActionLabel}
				</Link>
			</div>
		</div>
	);
}
