// apps/web-sveltekit/src/lib/components/pageComponents/articlePageComponent.svelte
<script lang="ts">
	import { components } from "../portableText/components";
	import { PortableText } from "@portabletext/svelte";
	import type { Article } from "common/src/types/sanity/article";

	export let article: Article;
</script>

<h1>{article.title}</h1>
<PortableText value={article.blocks.body} {components} />

// apps/next-website-app-dir-intl/lib/components/pageComponents/articlePageComponent/index.tsx
import { portableTextArticleComponents } from "@/lib/components/portableText";
import { PortableText } from "@portabletext/react";
import { Article as ArticlePageType } from "common/src/types/sanity/article";

interface Props {
	articlePageDocument: ArticlePageType;
}

/**
 * This component is responsible for rendering an article page
 * Most of the work here is performed by the <PortableText> Sanity module.
 * The «portableTextArticleComponents» serializer rules are passed in to <PortableText>
 * to inform the module how it should render each component or mark
 */
export default function ArticleComponent({ articlePageDocument }: Props): JSX.Element {
	return (
		<div>
			<h1>{articlePageDocument.title}</h1>
			<PortableText
				value={articlePageDocument.blocks.body}
				components={portableTextArticleComponents}
			/>
		</div>
	);
}
