// apps/web-sveltekit/src/routes/articles/[collection]/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types";

	export let data: PageData;
</script>

<h2>Articles in collection «{data.articles[0].collection.name}»</h2>
<ul>
	{#each data.articles as article}
		<li><a href={`/articles/${article.collection.path.current}/${article.slug}`}>{article.title}</a></li>
	{/each}
</ul>

// apps/next-website-app-dir/app/articles/[collection]/page.tsx
import { sanityConfig } from "@/lib/config/envVariables";
import { getAllArticlesForCollection } from "common/src/content/sanity/articles";
import Link from "next/link";

async function getData(collection: string) {
	const allArticles = await getAllArticlesForCollection(sanityConfig, collection);
	return allArticles;
}

interface Params {
	collection: string;
}

export default async function ArticleCollectionListPage({ params }: { params: Params }) {
	const allArticlePageDocuments = await getData(params.collection);

	return (
		<>
			<h1>Article list for collection {allArticlePageDocuments[0].collection.name}</h1>
			<ul>
				{allArticlePageDocuments.map((article) => {
					return (
						<li key={article._id}>
							<Link href={`articles/${article.collection.path.current}/${article.slug}`}>
								{article.title}
							</Link>
						</li>
					);
				})}
			</ul>
		</>
	);
}
