// apps/web-sveltekit/src/lib/components/portableText/youtube.svelte
<script lang="ts">
	import type { CustomBlockComponentProps } from "@portabletext/svelte";
	import getYouTubeId from "get-youtube-id";

	export let portableText: CustomBlockComponentProps;

	const videoId = getYouTubeId(portableText.value.url);
</script>

<div class="aspect-video">
	<iframe
		title="Video"
		src={`https://www.youtube.com/embed/${videoId}`}
		class="aspect-video w-full"
		frameBorder="0"
		allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
		allowFullScreen
	/>
</div>

// apps/sanity-studio/schemas/objects/blockContent/youtube.tsx
import getYouTubeId from "get-youtube-id";
import React from "react";
import { ImYoutube2 } from "react-icons/im";
import YouTube from "react-youtube";

const Preview = ({ value }) => {
    const { url } = value;
    const id = getYouTubeId(url);
    return <YouTube videoId={id} />;
};

export default {
    type: "object",
    title: "YouTube",
    name: "youtube",
    icon: ImYoutube2,
    fields: [
        {
            name: "title",
            title: "Video title",
            type: "string",
            validation: (Rule: { required: () => any }) => Rule.required(),
        },
        {
            name: "url",
            title: "YouTube video url",
            type: "string",
            description:
                "Paste the url from the youtube video you want to embed (https://www.youtube.com/watch?v=XXXXXXXXXXX)",
            validation: (Rule: { required: () => any }) => Rule.required(),
        },
    ],
    preview: {
        select: {
            url: "url",
        },
        component: Preview,
    },
};
