// apps/web-sveltekit/src/lib/components/pageComponents/articlePageComponent.svelte
<script lang="ts">
	import { components } from "../portableText/components";
	import { PortableText } from "@portabletext/svelte";
	import type { Article } from "common/src/types/sanity/article";

	export let article: Article;
</script>

<h1>{article.title}</h1>
<PortableText value={article.blocks.body} {components} />

// apps/next-website/lib/components/pageComponents/articlePageComponent/index.tsx
import { PortableText } from "@portabletext/react";

import { portableTextArticleComponents } from "@/lib/components/portableText";
import { Article as ArticlePageType } from "@/lib/types/sanity/article";

interface Props {
	articlePageDocument: ArticlePageType;
}

export default function ArticleComponent({ articlePageDocument }: Props): JSX.Element {
	return (
		<div>
			<h1>Article page {articlePageDocument.title}</h1>
			<PortableText value={articlePageDocument.blocks.body} components={portableTextArticleComponents} />
		</div>
	);
}
