// apps/web-sveltekit/src/lib/components/portableText/youtube.svelte
<script lang="ts">
	import type { CustomBlockComponentProps } from "@portabletext/svelte";
	import getYouTubeId from "get-youtube-id";

	export let portableText: CustomBlockComponentProps;

	const videoId = getYouTubeId(portableText.value.url);
</script>

<div class="aspect-video">
	<iframe
		title="Video"
		src={`https://www.youtube.com/embed/${videoId}`}
		class="aspect-video w-full"
		frameBorder="0"
		allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
		allowFullScreen
	/>
</div>

// apps/next-website/lib/components/portableText/youtube/index.tsx
import getYouTubeId from "get-youtube-id";

interface Props {
    url: string;
}

/**
 * YouTube component used to display a YouTube video embedded as block content in Sanity
 */
export default function YouTubeComp({ url }: Props): JSX.Element {
    const videoId = getYouTubeId(url);
    return (
        <div className="aspect-video">
            <iframe
                src={`https://www.youtube.com/embed/${videoId}`}
                className="w-full aspect-video"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
            ></iframe>
        </div>
    );
}
