// apps/next-website-app-dir/lib/components/mainMenu/index.tsx
import SchemaType from "common/src/sanity/SchemaType";
import type { MainMenu } from "common/src/types/sanity/allPages/mainMenu";
import Link from "next/link";
import Alert from "ui/Alert";

interface Props {
	mainMenuData: MainMenu;
	previewActive?: boolean;
}

export default function MainMenuComp({ mainMenuData, previewActive }: Props): JSX.Element {
	const items = mainMenuData.menuItems.map((item) => {
		if (item._type === SchemaType.MAIN_MENU_ACTION_ITEM_OBJECT) {
			return (
				<li key={item._key}>
					<Link href={item.url}>{item.label}</Link>
				</li>
			);
		} else {
			return (
				<li key={item._key} tabIndex={0}>
					<a>
						{item.label}
						<svg
							className="fill-current"
							xmlns="http://www.w3.org/2000/svg"
							width="20"
							height="20"
							viewBox="0 0 24 24"
						>
							<path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
						</svg>
					</a>
					<ul className="bg-base-200 p-2">
						{item.subItems.map((subItem) => {
							if (subItem.url.startsWith("http")) {
								return (
									<li key={subItem._key}>
										<a href={subItem.url} target="_blank" rel="noreferrer">
											{subItem.label}
										</a>
									</li>
								);
							}
							return (
								<li key={subItem._key}>
									<Link href={subItem.url}>{subItem.label}</Link>
								</li>
							);
						})}
					</ul>
				</li>
			);
		}
	});

	return (
		<header className="bg-slate-500">
			{previewActive && (
				<Alert alertType="warn">
					Preview is active {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
					<a href="/api/exit-preview" className="text-blue-400 underline">
						Disable preview mode
					</a>
				</Alert>
			)}
			<nav className="navbar bg-base-200">
				<div className="flex-none">
					<ul className="menu menu-horizontal px-1">{items}</ul>
				</div>
			</nav>
		</header>
	);
}

// apps/web-sveltekit-intl/src/lib/components/mainMenu/mainMenu.svelte
<script lang="ts">
	// Imports
	import LocalePicker from "./localePicker.svelte";
	import MainMenuItem from "./mainMenuItem.svelte";
	import type { MainMenu } from "common/src/types/sanity/allPages/mainMenu";

	// Props
	export let mainMenuData: MainMenu;
	export let previewActive: boolean;
</script>

<header class="bg-slate-500">
	{#if previewActive}
		<div class="alert alert-info shadow-lg">
			<div>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					class="h-6 w-6 flex-shrink-0 stroke-current"
					><path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
					/></svg
				>
				<span>Preview is active.</span>
				<a href="/api/exit-preview" class="text-blue-400 underline"> Disable preview mode </a>
			</div>
		</div>
	{/if}

	<nav class="navbar bg-base-200">
		<div class="flex-none">
			<ul class="menu menu-horizontal px-1">
				{#each mainMenuData.menuItems as mainMenuItem}
					<MainMenuItem {mainMenuItem} />
				{/each}
				<LocalePicker />
			</ul>
		</div>
	</nav>
</header>
