// apps/next-website/lib/components/globalComponents/infoBox.tsx
import { GlobalInfoBox } from "@/lib/types/sanity/globalComponents/infoBox";

interface Props {
	infoBoxProps: GlobalInfoBox;
}

export default function GlobalCompInfoBox({ infoBoxProps }: Props) {
	const { title, infoText } = infoBoxProps;
	return (
		<div className="border border-gray-700 p-4">
			<div>
				<h3 className="mt-2">{title}</h3>
				<p className="">{infoText}</p>
			</div>
		</div>
	);
}

// apps/web-sveltekit-intl/src/lib/components/globalComponents/infoBox.svelte
<script lang="ts">
	// imports
	import type { GlobalInfoBox } from "common/src/types/sanity/globalComponents/infoBox";

	// props
	export let infoBoxData: GlobalInfoBox;
</script>

<div class="border border-gray-700 p-4">
	<div>
		<h3 class="mt-2">{infoBoxData.title}</h3>
		<p class="">{infoBoxData.infoText}</p>
	</div>
</div>
